# Generated by Django 4.1 on 2022-08-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_alter_users_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-id']},
        ),
    ]
