# Generated by Django 4.1 on 2022-08-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
